### ISSUE TITLE
[BUG] Generate Identities does not working

### ISSUE THREAD

**Issue by justmert** [tolgayayci/sora#4]
**Describe the bug**
While generating identities,  just filling `identity name` and leaving others empty does not generate identity and does not show any error.

**To Reproduce**
1. Go to `Identities`
2. Click on `Create New Identity`
3. In newly opened pop-up, fill `Identity Name`
4. Click on `Create`
5. pop-up window suddenly closes and does not show any error.

**Expected behavior**
An error or newly created identity.

**Screenshots**
<img width="505" alt="image" src="https://github.com/tolgayayci/soroban-cli-gui/assets/37740842/d7898e9c-5f09-4ae2-8ad6-4f70d0b291f8">

**Desktop (please complete the following information):**
 - OS: macOS (Apple Silicon)
 - Soroban Version: 0.23.0
 - App Version: 0.1.0

**Comment by tolgayayci** [comment]
Network, network phrase and rpc url also set as required, problem solved.
