### ISSUE TITLE
[FEAT] Include tracking metrics

### ISSUE THREAD

**Issue by justmert** [tolgayayci/sora#8]
**Is your feature request related to a problem? Please describe.**
Currently we do not see,
* How many actively using the application?
* Which pages they prefer to visit frequently?

etc. Implementation tracker would give these insights anonymously.

**Describe the solution you'd like**
Implementation of the tracker.

**Comment by tolgayayci** [comment]
@aptabase integrated and works well with anonymously, collects page visits and some specific details like commands, interactions and so on.
